# Default values for surfingcat-trading-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: trading-spa
  tag: latest
  pullPolicy: Never

persistence:
  enabled: true
  localPath: /Users/surfingcat/go_hub/src/github.com/yellowred/surfingcat-trading-bot/client

mongo:
  host: mongodb
